version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_lf1.zip .
      - zip -r9 ../deployment_package_lf2.zip .
      - cd ..
      - cd lambda
      - mv LF1.py lambda_function.py
      - zip -g deployment_package_lf1.zip lambda_function.py
      - mv lambda_function.py LF1.py
      - mv LF2.py lambda_function.py
      - zip -g deployment_package_lf2.zip lambda_function.py
      - mv lambda_function.py LF2.py
  post_build:
    commands:
      - echo "Updating LF1 and LF2"
      - aws lambda update-function-code --function-name LF1-Final --zip-file fileb://deployment_package_lf1.zip
      - aws lambda update-function-code --function-name picSearchCFN --zip-file fileb://deployment_package_lf2.zip
      - echo "DONE."